version: "3"

services:
  frontend:
    container_name: frontend
    environment:
      - ENABLE_TELEMETRY=false
    build:
      context: .
      dockerfile: ./frontend/Dockerfile

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    environment:
      - PORT=${WEBSITE_PORT}
      - CAPTCHA_SECRET=${CAPTCHA_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DATABASE_URI=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@databasePostgres:${DATABASE_PORT}/default
      - GHOST_KEY=${GHOST_KEY}
    volumes:
      - ./backend/src:/srv/app/bremauer-backend/src

networks:
  default:
    external:
      name: website-network
