kind: pipeline
type: docker
name: portfolio-cicd

steps:
  - name: Deployment
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - docker-compose build
      - docker-compose down
      - docker-compose up -d
      - docker system prune -a -f
    environment:
      WEBSITE_PORT:
        from_secret: WEBSITE_PORT
      DATABASE_USER:
        from_secret: DATABASE_USER
      DATABASE_PASSWORD:
        from_secret: DATABASE_PASSWORD
      DATABASE_PORT:
        from_secret: DATABASE_PORT
      MAIL_USERNAME:
        from_secret: MAIL_USERNAME
      MAIL_PASSWORD:
        from_secret: MAIL_PASSWORD
      GHOST_KEY:
        from_secret: GHOST_KEY

trigger:
  branch:
    - main
    - dev
  event:
    - push

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock