# This workflow will build a Node.js project with Webpack
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-javascript

name: Build react app

# This workflow gets triggered on every push, except for the 'main' and 'dev' branches
on:
  push:
    branches-ignore:
      - "main"
      - "dev"

jobs:
  build-react:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # This job will run on Node.js versions 14.x, 16.x, and 18.x
        node-version: [14.x, 16.x, 18.x]

    steps:
    # This step checks out a copy of your repository
    - uses: actions/checkout@v3

    # This step sets up a Node.js environment with the specified version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # This step builds your Node.js project
    - name: Build
      run: |
        npm install
        npm run build
      working-directory: ./frontend